#!/bin/bash

# Source this before running SDPO examples from this repository.

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export MEGATRON_PATH="${MEGATRON_PATH:-${PROJECT_ROOT}/third_party/Megatron-LM}"

export PYTHONPATH="${PROJECT_ROOT}:${MEGATRON_PATH}:${PYTHONPATH:-}"

sdpo_cuda_version_major() {
   local path="$1"
   local version=""
   if [ -f "${path}/include/cuda.h" ]; then
      version="$(sed -n 's/^#define CUDA_VERSION[[:space:]]\+\([0-9]\+\).*/\1/p' "${path}/include/cuda.h" | head -n 1)"
   fi
   [ -n "$version" ] || return 1
   echo $((version / 1000))
}

sdpo_driver_cuda_major() {
   if [ -n "${SDPO_DRIVER_CUDA_MAJOR:-}" ]; then
      echo "$SDPO_DRIVER_CUDA_MAJOR"
      return 0
   fi
   if command -v nvidia-smi >/dev/null 2>&1; then
      nvidia-smi 2>/dev/null | sed -n 's/.*CUDA Version:[[:space:]]*\([0-9]\+\).*/\1/p' | head -n 1
   fi
}

sdpo_nvcc_version_major() {
   local path="$1"
   if [ -x "${path}/bin/nvcc" ]; then
      "${path}/bin/nvcc" --version 2>/dev/null | sed -n 's/.*release \([0-9]\+\).*/\1/p' | head -n 1
   fi
}

sdpo_cuda_nvcc_matches_headers() {
   local path="$1"
   local cuda_major nvcc_major
   cuda_major="$(sdpo_cuda_version_major "$path" 2>/dev/null || true)"
   nvcc_major="$(sdpo_nvcc_version_major "$path" 2>/dev/null || true)"
   if [ -z "$cuda_major" ] || [ -z "$nvcc_major" ]; then
      return 0
   fi
   [ "$nvcc_major" -le "$cuda_major" ]
}

sdpo_cuda_candidate_supported() {
   local path="$1"
   local cuda_major driver_major
   if [ "${SDPO_ALLOW_UNSUPPORTED_CUDA_TOOLKIT:-false}" = "true" ]; then
      return 0
   fi
   cuda_major="$(sdpo_cuda_version_major "$path" 2>/dev/null || true)"
   driver_major="$(sdpo_driver_cuda_major 2>/dev/null || true)"
   if [ -z "$cuda_major" ] || [ -z "$driver_major" ]; then
      return 0
   fi
   [ "$cuda_major" -le "$driver_major" ]
}

sdpo_full_cuda_candidate_supported() {
   local path="$1"
   sdpo_cuda_candidate_supported "$path" && sdpo_cuda_nvcc_matches_headers "$path"
}

SDPO_RUNTIME_ENV_FILE="${SDPO_RUNTIME_ENV_FILE:-${PROJECT_ROOT}/examples/sdpo/.runtime/env.sh}"
if [ -f "$SDPO_RUNTIME_ENV_FILE" ]; then
   # Generated by examples/sdpo/preflight.sh.
   source "$SDPO_RUNTIME_ENV_FILE"
fi
if [ -n "${CUDA_HOME:-}" ] && ! sdpo_cuda_candidate_supported "$CUDA_HOME"; then
   unset CUDA_HOME CUDA_PATH
   unset SGLANG_ENABLE_JIT_DEEPGEMM
   unset SGLANG_ENABLE_JIT_KVCACHE
   unset SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM
fi
if [ -n "${CUDA_HOME:-}" ] && { [ ! -d "${CUDA_HOME}/include" ] || [ ! -d "${CUDA_HOME}/lib" ]; }; then
   unset CUDA_HOME
fi

# SGLang imports deep_gemm during Megatron weight-update setup. Prefer a full
# CUDA toolkit when one is visible; otherwise fall back to the runtime bundled
# with the Python environment.
if [ -z "${CUDA_HOME:-}" ]; then
   CUDA_CANDIDATES=(
      "${CUDA13_HOME:-}"
      "${CUDA12_HOME:-}"
      /usr/local/cuda-13
      /usr/local/cuda-13.0
      /usr/local/cuda
      /usr/local/cuda-12.4
      "${PROJECT_ROOT}"/.venv/lib/python*/site-packages/nvidia/cuda_runtime
      "${PROJECT_ROOT}"/.venv/lib/python*/site-packages/nvidia/cu13
   )
   for candidate in "${CUDA_CANDIDATES[@]}"; do
      if [ -n "$candidate" ] && [ -d "${candidate}/include" ] && [ -d "${candidate}/lib" ] && [ -x "${candidate}/bin/nvcc" ] && sdpo_full_cuda_candidate_supported "$candidate"; then
         export CUDA_HOME="$candidate"
         break
      fi
   done
   if [ -z "${CUDA_HOME:-}" ]; then
      for candidate in "${CUDA_CANDIDATES[@]}"; do
         if [ -n "$candidate" ] && [ -d "${candidate}/include" ] && [ -d "${candidate}/lib" ] && sdpo_cuda_candidate_supported "$candidate"; then
            export CUDA_HOME="$candidate"
            break
         fi
      done
   fi
   unset CUDA_CANDIDATES
fi
if [ -n "${CUDA_HOME:-}" ]; then
   export CUDA_PATH="${CUDA_PATH:-$CUDA_HOME}"
   export LD_LIBRARY_PATH="${CUDA_HOME}/lib:${LD_LIBRARY_PATH:-}"
   if [ -d "${CUDA_HOME}/lib64" ]; then
      export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"
   fi
   if [ -d "${CUDA_HOME}/bin" ]; then
      export PATH="${CUDA_HOME}/bin:${PATH}"
   fi
fi

export PYTORCH_ALLOC_CONF="${PYTORCH_ALLOC_CONF:-expandable_segments:True}"

# The shared home/cache paths on some clusters are read-only inside this
# workspace. Keep runtime caches in writable locations unless the caller
# explicitly provides a writable override.
if [ -z "${XDG_CACHE_HOME:-}" ] || ! mkdir -p "$XDG_CACHE_HOME" 2>/dev/null || [ ! -w "$XDG_CACHE_HOME" ]; then
   export XDG_CACHE_HOME="/tmp/${USER:-miles}-cache"
fi
if [ -z "${HF_HOME:-}" ] || ! mkdir -p "$HF_HOME" 2>/dev/null || [ ! -w "$HF_HOME" ]; then
   export HF_HOME="${XDG_CACHE_HOME}/huggingface"
fi
if [ -z "${TRANSFORMERS_CACHE:-}" ] || ! mkdir -p "$TRANSFORMERS_CACHE" 2>/dev/null || [ ! -w "$TRANSFORMERS_CACHE" ]; then
   export TRANSFORMERS_CACHE="${HF_HOME}/transformers"
fi
if [ -z "${FLASHINFER_WORKSPACE_BASE:-}" ] || ! mkdir -p "$FLASHINFER_WORKSPACE_BASE" 2>/dev/null || [ ! -w "$FLASHINFER_WORKSPACE_BASE" ]; then
   export FLASHINFER_WORKSPACE_BASE="${XDG_CACHE_HOME}"
fi
if [ -z "${UV_CACHE_DIR:-}" ] || ! mkdir -p "$UV_CACHE_DIR" 2>/dev/null || [ ! -w "$UV_CACHE_DIR" ]; then
   export UV_CACHE_DIR="/tmp/uv-cache"
fi

mkdir -p "$XDG_CACHE_HOME" "$HF_HOME" "$TRANSFORMERS_CACHE" "$FLASHINFER_WORKSPACE_BASE" "$UV_CACHE_DIR"

# Keep non-JIT fallback on runtime-only CUDA installs. Once preflight finds or
# installs a real nvcc, use JIT-capable defaults.
if [ -n "${CUDA_HOME:-}" ] && [ -x "${CUDA_HOME}/bin/nvcc" ] && [ "${SDPO_DISABLE_SGLANG_JIT:-false}" != "true" ]; then
   export SGLANG_ENABLE_JIT_DEEPGEMM="${SGLANG_ENABLE_JIT_DEEPGEMM:-1}"
   export SGLANG_ENABLE_JIT_KVCACHE="${SGLANG_ENABLE_JIT_KVCACHE:-1}"
   export SGLANG_JIT_DEEPGEMM_PRECOMPILE="${SGLANG_JIT_DEEPGEMM_PRECOMPILE:-0}"
   export SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM="${SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM:-${SDPO_ENABLE_BATCH_INVARIANT_DEEPGEMM:-0}}"
else
   export SGLANG_ENABLE_JIT_DEEPGEMM="${SGLANG_ENABLE_JIT_DEEPGEMM:-0}"
   export SGLANG_ENABLE_JIT_KVCACHE="${SGLANG_ENABLE_JIT_KVCACHE:-0}"
   export SGLANG_JIT_DEEPGEMM_PRECOMPILE="${SGLANG_JIT_DEEPGEMM_PRECOMPILE:-0}"
   export SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM="${SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM:-0}"
fi
